### ISSUE TITLE
Profile Picture not working since Facebook API Update

### ISSUE THREAD

**Issue by corentios** [JeffResc/ShortLook-Messenger#2]
Since the new Messenger update (with the new logo) when I receive a message I have the default profile picture from Facebook.

By the way : My contacts have a profile picture.

![image](https://user-images.githubusercontent.com/43886135/97513704-3e39f180-198d-11eb-8468-ab82293734e3.png)

**Comment by corentios** [comment]
According to this Stack Overflow problem : https://meta.stackoverflow.com/questions/402378/today-i-visited-stack-overflow-and-my-profile-picture-has-vanished-but-i-didn

"Looks like Facebook changed the requirements for accessing profile images. I don't have much else to offer right now, we'll need to investigate further."

**Comment by JeffResc** [comment]
Hey @CorentiOS,

Sorry about the troubles you’re having here. Looks like Facebook updated their API that this used in order to fetch the images. I’m in the process of creating a Facebook business page, but it looks like it needs to verify that this is a real business before I can do that, which is hard for an open-source project like this. I’ll see what I can do to get this working and I’ll update you here as I begin to fix this...

**Comment by loonsies** [comment]
Hello,
Any news about this issue?

**Comment by JeffResc** [comment]
@senolem Unfortunately, no. Facebook rejected my business verification with no message so I’m unsure as to why. I’ll need to find another way to go about this, which I am still thinking on how to do. If you have any suggestions, please don’t hesitate to let me know.

**Comment by loonsies** [comment]
@JeffResc Well I tried to create a page for a clothing business without any problem, and I can create an app too on Facebook Dev. all of this with my personal account and without any verification, so I’m not sure about what verification you are talking about but the API documentation says « User or Page access token for Facebook Login authenticated requests » so maybe each ShortLook user could generate an user access token with their own Facebook profile if you can’t get a page one ?

**Comment by loonsies** [comment]
I've looked a bit further and I could get a page access token as well as a client access token without any approval needed. 

![test](https://user-images.githubusercontent.com/37041587/99901325-506e2d80-2cb6-11eb-9246-890e7d498786.png)
I can give you mine if you can't get one, as I won't use it :)

**Comment by JeffResc** [comment]
@senolem Could you explain or link instructions to show how you did this without approval?

**Comment by loonsies** [comment]
@JeffResc Absolutely! I’ll make a little tutorial with screenshots

**Comment by JeffResc** [comment]
@senolem Actually - hold that thought. I've been working on something and I might have it working in just a little bit here...

**Comment by loonsies** [comment]
No problem 👍

**Comment by loonsies** [comment]
In case you haven't figured out, sorry for the french language !
1.	Go to my apps and create an app
![1](https://user-images.githubusercontent.com/37041587/100374621-d965cb80-300c-11eb-89aa-811e5a744ff6.png)

2.	Chose the first choice
![2](https://user-images.githubusercontent.com/37041587/100374646-e387ca00-300c-11eb-95a7-5a0c2c47a315.png)

3.	Just enter an app name and select Myself or my own business in the app’s goal then create the app 
![3](https://user-images.githubusercontent.com/37041587/100374666-e84c7e00-300c-11eb-8521-af1e3765bc02.png)

4.	Go into Tools and select Access token tool  
![4](https://user-images.githubusercontent.com/37041587/100374671-eb476e80-300c-11eb-9201-673c2c1768e1.png)

5.	Here is your app token, click on give authorizations to your app to get an user token 
![5](https://user-images.githubusercontent.com/37041587/100374678-ee425f00-300c-11eb-8213-2a2b7220542b.png)

6.	Done !
 
![6](https://user-images.githubusercontent.com/37041587/100374688-f00c2280-300c-11eb-8506-c1d64682688e.png)

**Comment by JeffResc** [comment]
@CorentiOS @senolem I'm happy to report that I think I've got it working again in version 1.1.0. It's been submitted to the Dynastic Repo and is currently pending their review before it can be publicly viewed. It should be available shortly, but if you can't wait, you can always download the DEB directly from the releases page:

https://github.com/JeffResc/ShortLook-Messenger/releases/tag/v1.1.0

**Comment by JeffResc** [comment]
I'm also going to go ahead and close this issue. If you have any further issues, feel free to open this one back up or create a new one 👍

**Comment by loonsies** [comment]
Amazing ! Thanks 
Edit : Doesn't work for me, it shows me messenger's icon

**Comment by corentios** [comment]
Thanks you !

**Comment by corentios** [comment]
> Amazing ! Thanks
> Edit : Doesn't work for me, it shows me messenger's icon

Same as you, the package name is Facebook Messenger Profile Picture for Shortlook, and the oldest tweak name was Messenger Profile Picture for Shortlook

I don't know if there is a conflit

@JeffResc

**Comment by JeffResc** [comment]
I'm sorry it isn't working and I'm not sure why. Since I'm not able to reproduce this myself, would either of you mind installing a test version just so I can see if there are any differences?

First uninstall this ShortLook provider completely, then install the test provider from [this link](https://drive.google.com/file/d/1bhBiRiAJMCsxpjZLaJX-yahyu406yjM3/view?usp=drivesdk) and be sure to restart SpringBoard.

Once installed, receive a Messenger notification, but make sure that the ShortLook animation plays (i.e. the device is locked). Then it should show a pop-up similar to this:

![Pop-up](https://i.imgur.com/4U5oGLZ_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

From there, please take a screenshot and upload it here. Note that there will be some sensitive information in there such as your profile ID and the sender's profile ID. You can feel free to censor those as I'm only interested in seeing the structure of where the `a` value is.

Let me know if you have any questions.

**Comment by corentios** [comment]
https://image.prntscr.com/image/-tZOlLxdTPiDnCWnGoUkLQ.png


Take it

**Comment by JeffResc** [comment]
@CorentiOS Thanks — Looks like I've identified the issue. It seems like your ID is located at `rp.p.a` while mine is located just at `p.a` I'll add some code to check where it is and I'll update here once that becomes available.

**Comment by JeffResc** [comment]
@CorentiOS — Thanks for the help. [Could you try this file](https://github.com/JeffResc/ShortLook-Messenger/releases/download/v1.1.1/com.jeffresc.shortlook.plugin.contact-photo.messenger_1.1.1_iphoneos-arm.deb)? This is beta for v1.1.1 which will be v1.1.1 as long as this works 👍

**Comment by corentios** [comment]
Perfect, it's working ! 

Thanks you so much !

**Comment by JeffResc** [comment]
Great, I'll publish it to the releases here on GitHub and upload it to Dynastic ASAP.
